name: MeetHourSDKTest
description: Demonstrates how to use the Meet Hour Flutter plugin.
version: 0.1.2
publish_to: 'none'


environment:
  sdk: '>=2.17.0'

dependencies:
  flutter:
    sdk: flutter

  meet_hour: '>=5.0.31'

  cupertino_icons: ^1.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  syncfusion_flutter_datepicker: ^24.1.41

  flutter_datetime_picker_plus: ^2.1.0
  dropdown_search: ^5.0.6
  shared_preferences: ^2.2.2
  flutter_native_timezone:
    git:
      url: https://github.com/iamzeeshanali/flutter_native_timezone.git
      ref: 59e26fcee72a24f3770c0719f111950eb4f885f7 # commit hash
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
